# Generated by Django 2.2.6 on 2019-10-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrappers', '0002_auto_20191005_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
    ]
