# Generated by Django 2.2.6 on 2019-10-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappers', '0003_remove_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
