# Generated by Django 2.2.6 on 2019-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappers', '0004_auto_20191005_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
