# Generated by Django 2.2.6 on 2019-10-05 22:49

from django.conf import settings
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrappers', '0007_remove_content_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scrapper',
            new_name='Rss',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-favourite']},
        ),
        migrations.AlterModelManagers(
            name='content',
            managers=[
                ('favourites', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='scrapper',
            new_name='rss',
        ),
    ]
